[project]
name = "example"
description = "Everyting else is omitted for brevity"
dependencies = [
    "django>=4",
    "pytest>=7",
]
optional-dependencies = { http = ['requests>=2.20', 'httpx>=0.20.0'] }
