name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: pip install -r requirements-linting.txt

    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files

  test_action:
    runs-on: ubuntu-latest

    outputs:
      PYTHON_DEPENDENCY_CASES: ${{ steps.list-python-dependencies.outputs.PYTHON_DEPENDENCY_CASES }}

    steps:
    - uses: actions/checkout@v3

    - uses: samuelcolvin/list-python-dependencies@main
      id: list-python-dependencies
      with:
        max_cases: 10
        path: ./test-case/

  test_matrix:
    runs-on: ubuntu-latest

    needs:
      - test_action

    strategy:
      matrix:
        PYTHON_DEPENDENCY_CASE: ${{ fromJSON(needs.test_action.outputs.PYTHON_DEPENDENCY_CASES) }}

    name: testing ${{ matrix.PYTHON_DEPENDENCY_CASE }}
    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install ${{ matrix.PYTHON_DEPENDENCY_CASE }}
      - run: pip freeze
